# Generated by Django 3.1.2 on 2020-10-21 07:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50, verbose_name='ИНН')),
        ),
    ]
